---
- name: Setup WSL Environment
  hosts: localhost
  connection: local
  become: true

  vars:
    user_name: jano
    user_home: "/home/{{ user_name }}"

  tasks:
    - name: Ensure required packages are installed
      apt:
        name:
          - git
          - curl
          - vim
          - htop
          - ripgrep
          - unzip
          - bind9-dnsutils
        state: present
        update_cache: yes

    - name: Install wsl2-ssh-agent
      get_url:
        url: https://github.com/mame/wsl2-ssh-agent/releases/latest/download/wsl2-ssh-agent
        dest: /usr/local/bin/wsl2-ssh-agent
        mode: '0755'
        owner: root
        group: root

    - name: Configure wsl2-ssh-agent in .bashrc
      become_user: "{{ user_name }}"
      lineinfile:
        path: "{{ user_home }}/.bashrc"
        line: "eval $(/usr/local/bin/wsl2-ssh-agent)"
        state: present
        create: yes

    - name: Install uv in user mode
      become_user: "{{ user_name }}"
      shell: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
      args:
        creates: "{{ user_home }}/.local/bin/uv"

    - name: Create test file to verify execution
      ansible.builtin.copy:
        content: "The ansible playbook was correctly executed."
        dest: "{{ user_home }}/ansible_test_file.txt"
        owner: jano
        group: jano
        mode: '0644'
