---
- name: Setup WSL Environment
  hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Ensure required packages are installed
      apt:
        name:
          - git
          - curl
          - vim
          - htop
          - ripgrep
          - unzip
        state: present
        update_cache: yes
